version: '2'

services:
  postgresql:
      image: postgres:9.5.5
      ports: 
          - "5432:5432"
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=local
  main:
      image: instore/koa-server
      command: npm run server:dev
      ports:
        - "8080:8080"
      links:
        - postgresql
      volumes:
        - ./:/usr/src/app